worker_processes 1;

events {
    worker_connections 1024;
}

http {

    upstream user_service {
        server 127.0.0.1:8081;
    }

    upstream catalog_service {
        server 127.0.0.1:8082;
    }

    upstream cart_service {
        server 127.0.0.1:8083;
    }

    upstream order_service {
        server 127.0.0.1:8084;
    }

    upstream inventory_service {
        server 127.0.0.1:8085;
    }

    server {
        listen 8080;

        location /api/auth {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/users {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/products {
            proxy_pass http://catalog_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/categories {
            proxy_pass http://catalog_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/carts {
            proxy_pass http://cart_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/orders {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/inventory {
            proxy_pass http://inventory_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
